# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XRRRedGUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 844)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.specWidget = QtWidgets.QListWidget(self.centralwidget)
        self.specWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.specWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.specWidget.setObjectName("specWidget")
        self.gridLayout_4.addWidget(self.specWidget, 1, 0, 1, 2)
        self.loadSpecButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadSpecButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.loadSpecButton.setObjectName("loadSpecButton")
        self.gridLayout_4.addWidget(self.loadSpecButton, 2, 0, 1, 1)
        self.deleteSpecButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteSpecButton.setObjectName("deleteSpecButton")
        self.gridLayout_4.addWidget(self.deleteSpecButton, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.backWidget = QtWidgets.QListWidget(self.centralwidget)
        self.backWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.backWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.backWidget.setObjectName("backWidget")
        self.gridLayout_3.addWidget(self.backWidget, 1, 0, 1, 2)
        self.loadBackButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadBackButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.loadBackButton.setObjectName("loadBackButton")
        self.gridLayout_3.addWidget(self.loadBackButton, 2, 0, 1, 1)
        self.deleteBackButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteBackButton.setObjectName("deleteBackButton")
        self.gridLayout_3.addWidget(self.deleteBackButton, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.slitWidget = QtWidgets.QListWidget(self.centralwidget)
        self.slitWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.slitWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.slitWidget.setObjectName("slitWidget")
        self.gridLayout_2.addWidget(self.slitWidget, 1, 0, 1, 2)
        self.loadSlitButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadSlitButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.loadSlitButton.setObjectName("loadSlitButton")
        self.gridLayout_2.addWidget(self.loadSlitButton, 2, 0, 1, 1)
        self.deleteSlitButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteSlitButton.setObjectName("deleteSlitButton")
        self.gridLayout_2.addWidget(self.deleteSlitButton, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.logWidget = QtWidgets.QListWidget(self.centralwidget)
        self.logWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.logWidget.setObjectName("logWidget")
        self.verticalLayout_3.addWidget(self.logWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.plotLayout = QtWidgets.QVBoxLayout()
        self.plotLayout.setObjectName("plotLayout")
        self.verticalLayout_5.addLayout(self.plotLayout)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1)
        self.yAxisLog = QtWidgets.QRadioButton(self.centralwidget)
        self.yAxisLog.setChecked(True)
        self.yAxisLog.setObjectName("yAxisLog")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.yAxisLog)
        self.gridLayout_5.addWidget(self.yAxisLog, 0, 1, 1, 1)
        self.yAxisLinear = QtWidgets.QRadioButton(self.centralwidget)
        self.yAxisLinear.setObjectName("yAxisLinear")
        self.buttonGroup_2.addButton(self.yAxisLinear)
        self.gridLayout_5.addWidget(self.yAxisLinear, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 1, 0, 1, 1)
        self.xAxisQ = QtWidgets.QRadioButton(self.centralwidget)
        self.xAxisQ.setChecked(True)
        self.xAxisQ.setObjectName("xAxisQ")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.xAxisQ)
        self.gridLayout_5.addWidget(self.xAxisQ, 1, 1, 1, 1)
        self.xAxis2Theta = QtWidgets.QRadioButton(self.centralwidget)
        self.xAxis2Theta.setObjectName("xAxis2Theta")
        self.buttonGroup.addButton(self.xAxis2Theta)
        self.gridLayout_5.addWidget(self.xAxis2Theta, 1, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.footprintRangeMin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.footprintRangeMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.footprintRangeMin.setDecimals(10)
        self.footprintRangeMin.setMinimum(-1e+36)
        self.footprintRangeMin.setMaximum(1e+37)
        self.footprintRangeMin.setObjectName("footprintRangeMin")
        self.verticalLayout_6.addWidget(self.footprintRangeMin)
        self.gridLayout.addLayout(self.verticalLayout_6, 4, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.footprintRangeMax = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.footprintRangeMax.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.footprintRangeMax.setDecimals(10)
        self.footprintRangeMax.setMinimum(-1e+36)
        self.footprintRangeMax.setMaximum(1e+37)
        self.footprintRangeMax.setObjectName("footprintRangeMax")
        self.verticalLayout_7.addWidget(self.footprintRangeMax)
        self.gridLayout.addLayout(self.verticalLayout_7, 4, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.footprintRangeFull = QtWidgets.QPushButton(self.centralwidget)
        self.footprintRangeFull.setObjectName("footprintRangeFull")
        self.verticalLayout_8.addWidget(self.footprintRangeFull)
        self.footprintRangeFromGraph = QtWidgets.QPushButton(self.centralwidget)
        self.footprintRangeFromGraph.setObjectName("footprintRangeFromGraph")
        self.verticalLayout_8.addWidget(self.footprintRangeFromGraph)
        self.gridLayout.addLayout(self.verticalLayout_8, 4, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.footprintCalcMax = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.footprintCalcMax.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.footprintCalcMax.setDecimals(10)
        self.footprintCalcMax.setMinimum(-1e+36)
        self.footprintCalcMax.setMaximum(1e+37)
        self.footprintCalcMax.setObjectName("footprintCalcMax")
        self.verticalLayout_2.addWidget(self.footprintCalcMax)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 1, 1, 1)
        self.footprintApply = QtWidgets.QPushButton(self.centralwidget)
        self.footprintApply.setObjectName("footprintApply")
        self.gridLayout.addWidget(self.footprintApply, 7, 0, 1, 3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.footprintCalcMin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.footprintCalcMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.footprintCalcMin.setDecimals(10)
        self.footprintCalcMin.setMinimum(-1e+36)
        self.footprintCalcMin.setMaximum(1e+37)
        self.footprintCalcMin.setObjectName("footprintCalcMin")
        self.verticalLayout.addWidget(self.footprintCalcMin)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 3)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.footprintCalcGuess = QtWidgets.QPushButton(self.centralwidget)
        self.footprintCalcGuess.setObjectName("footprintCalcGuess")
        self.verticalLayout_9.addWidget(self.footprintCalcGuess)
        self.footprintCalcFromGraph = QtWidgets.QPushButton(self.centralwidget)
        self.footprintCalcFromGraph.setObjectName("footprintCalcFromGraph")
        self.verticalLayout_9.addWidget(self.footprintCalcFromGraph)
        self.gridLayout.addLayout(self.verticalLayout_9, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.footprintSlope = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.footprintSlope.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.footprintSlope.setDecimals(10)
        self.footprintSlope.setMinimum(-1e+55)
        self.footprintSlope.setMaximum(1e+57)
        self.footprintSlope.setObjectName("footprintSlope")
        self.verticalLayout_10.addWidget(self.footprintSlope)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.footprintIntercept = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.footprintIntercept.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.footprintIntercept.setDecimals(10)
        self.footprintIntercept.setMinimum(-1e+56)
        self.footprintIntercept.setMaximum(1e+55)
        self.footprintIntercept.setObjectName("footprintIntercept")
        self.verticalLayout_11.addWidget(self.footprintIntercept)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 3)
        self.combineScansButton = QtWidgets.QPushButton(self.centralwidget)
        self.combineScansButton.setObjectName("combineScansButton")
        self.gridLayout.addWidget(self.combineScansButton, 0, 0, 1, 3)
        self.verticalLayout_4.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 471, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1107, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionQ = QtWidgets.QAction(MainWindow)
        self.actionQ.setCheckable(True)
        self.actionQ.setChecked(True)
        self.actionQ.setObjectName("actionQ")
        self.action2Theta = QtWidgets.QAction(MainWindow)
        self.action2Theta.setCheckable(True)
        self.action2Theta.setObjectName("action2Theta")
        self.actionLinear = QtWidgets.QAction(MainWindow)
        self.actionLinear.setCheckable(True)
        self.actionLinear.setObjectName("actionLinear")
        self.actionLog = QtWidgets.QAction(MainWindow)
        self.actionLog.setCheckable(True)
        self.actionLog.setChecked(True)
        self.actionLog.setObjectName("actionLog")
        self.menuFile.addAction(self.actionExport)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadSpecButton.setText(_translate("MainWindow", "Load Specular"))
        self.deleteSpecButton.setText(_translate("MainWindow", "Delete"))
        self.label_4.setText(_translate("MainWindow", "Specular Scan"))
        self.loadBackButton.setText(_translate("MainWindow", "Load Background"))
        self.deleteBackButton.setText(_translate("MainWindow", "Delete"))
        self.label_5.setText(_translate("MainWindow", "Background Scan"))
        self.loadSlitButton.setText(_translate("MainWindow", "Load Slit"))
        self.deleteSlitButton.setText(_translate("MainWindow", "Delete"))
        self.label_6.setText(_translate("MainWindow", "Slit Scan"))
        self.label_13.setText(_translate("MainWindow", "Y-Axis"))
        self.yAxisLog.setText(_translate("MainWindow", "Log"))
        self.yAxisLinear.setText(_translate("MainWindow", "Linear"))
        self.label_14.setText(_translate("MainWindow", "X-Axis"))
        self.xAxisQ.setText(_translate("MainWindow", "Q"))
        self.xAxis2Theta.setText(_translate("MainWindow", "2Θ"))
        self.label_3.setText(_translate("MainWindow", "Footprint Correction"))
        self.label_8.setText(_translate("MainWindow", "Starting Q"))
        self.label_9.setText(_translate("MainWindow", "Starting Q"))
        self.footprintRangeFull.setText(_translate("MainWindow", "Full Range"))
        self.footprintRangeFromGraph.setText(_translate("MainWindow", "From Graph..."))
        self.label_2.setText(_translate("MainWindow", "Ending Q"))
        self.footprintApply.setText(_translate("MainWindow", "Apply"))
        self.label.setText(_translate("MainWindow", "Starting Q"))
        self.label_7.setText(_translate("MainWindow", "Correction Range"))
        self.footprintCalcGuess.setText(_translate("MainWindow", "Guess"))
        self.footprintCalcFromGraph.setText(_translate("MainWindow", "From Graph..."))
        self.label_10.setText(_translate("MainWindow", "Fit Parameters"))
        self.label_11.setText(_translate("MainWindow", "Slope"))
        self.label_12.setText(_translate("MainWindow", "Intercept"))
        self.combineScansButton.setText(_translate("MainWindow", "Combine Scans"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionExport.setText(_translate("MainWindow", "Export..."))
        self.actionQ.setText(_translate("MainWindow", "Q"))
        self.action2Theta.setText(_translate("MainWindow", "2Θ"))
        self.actionLinear.setText(_translate("MainWindow", "Linear"))
        self.actionLog.setText(_translate("MainWindow", "Log"))

