# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XRRRedGUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 844)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setMaximumSize(QtCore.QSize(300, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.specWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.specWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.specWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.specWidget.setObjectName("specWidget")
        self.verticalLayout_3.addWidget(self.specWidget)
        self.loadSpecButton = QtWidgets.QPushButton(self.layoutWidget)
        self.loadSpecButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.loadSpecButton.setObjectName("loadSpecButton")
        self.verticalLayout_3.addWidget(self.loadSpecButton)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setMaximumSize(QtCore.QSize(300, 16777215))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.backWidget = QtWidgets.QListWidget(self.layoutWidget1)
        self.backWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.backWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.backWidget.setObjectName("backWidget")
        self.verticalLayout_4.addWidget(self.backWidget)
        self.loadBackButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.loadBackButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.loadBackButton.setObjectName("loadBackButton")
        self.verticalLayout_4.addWidget(self.loadBackButton)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.slitWidget = QtWidgets.QListWidget(self.layoutWidget2)
        self.slitWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.slitWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.slitWidget.setObjectName("slitWidget")
        self.verticalLayout_5.addWidget(self.slitWidget)
        self.loadSlitButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.loadSlitButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.loadSlitButton.setObjectName("loadSlitButton")
        self.verticalLayout_5.addWidget(self.loadSlitButton)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 2, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.footprintCalcMin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.footprintCalcMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.footprintCalcMin.setDecimals(10)
        self.footprintCalcMin.setMinimum(-1e+36)
        self.footprintCalcMin.setMaximum(1e+37)
        self.footprintCalcMin.setObjectName("footprintCalcMin")
        self.verticalLayout.addWidget(self.footprintCalcMin)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.footprintCalcMax = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.footprintCalcMax.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.footprintCalcMax.setDecimals(10)
        self.footprintCalcMax.setMinimum(-1e+36)
        self.footprintCalcMax.setMaximum(1e+37)
        self.footprintCalcMax.setObjectName("footprintCalcMax")
        self.verticalLayout_2.addWidget(self.footprintCalcMax)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.footprintRangeMin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.footprintRangeMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.footprintRangeMin.setDecimals(10)
        self.footprintRangeMin.setMinimum(-1e+36)
        self.footprintRangeMin.setMaximum(1e+37)
        self.footprintRangeMin.setObjectName("footprintRangeMin")
        self.verticalLayout_6.addWidget(self.footprintRangeMin)
        self.gridLayout.addLayout(self.verticalLayout_6, 3, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.footprintRangeMax = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.footprintRangeMax.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.footprintRangeMax.setDecimals(10)
        self.footprintRangeMax.setMinimum(-1e+36)
        self.footprintRangeMax.setMaximum(1e+37)
        self.footprintRangeMax.setObjectName("footprintRangeMax")
        self.verticalLayout_7.addWidget(self.footprintRangeMax)
        self.gridLayout.addLayout(self.verticalLayout_7, 3, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.footprintRangeFull = QtWidgets.QPushButton(self.centralwidget)
        self.footprintRangeFull.setObjectName("footprintRangeFull")
        self.verticalLayout_8.addWidget(self.footprintRangeFull)
        self.footprintRangeFromGraph = QtWidgets.QPushButton(self.centralwidget)
        self.footprintRangeFromGraph.setObjectName("footprintRangeFromGraph")
        self.verticalLayout_8.addWidget(self.footprintRangeFromGraph)
        self.gridLayout.addLayout(self.verticalLayout_8, 3, 2, 1, 1)
        self.footprintApply = QtWidgets.QPushButton(self.centralwidget)
        self.footprintApply.setObjectName("footprintApply")
        self.gridLayout.addWidget(self.footprintApply, 4, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 3)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.footprintCalcGuess = QtWidgets.QPushButton(self.centralwidget)
        self.footprintCalcGuess.setObjectName("footprintCalcGuess")
        self.verticalLayout_9.addWidget(self.footprintCalcGuess)
        self.footprintCalcFromGraph = QtWidgets.QPushButton(self.centralwidget)
        self.footprintCalcFromGraph.setObjectName("footprintCalcFromGraph")
        self.verticalLayout_9.addWidget(self.footprintCalcFromGraph)
        self.gridLayout.addLayout(self.verticalLayout_9, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.logWidget = QtWidgets.QListWidget(self.centralwidget)
        self.logWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.logWidget.setObjectName("logWidget")
        self.gridLayout_2.addWidget(self.logWidget, 2, 0, 1, 1)
        self.plot = PlotWidget(self.centralwidget)
        self.plot.setObjectName("plot")
        self.gridLayout_2.addWidget(self.plot, 0, 1, 3, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 471, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1107, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuX_axis = QtWidgets.QMenu(self.menuOptions)
        self.menuX_axis.setObjectName("menuX_axis")
        self.menuY_Axis = QtWidgets.QMenu(self.menuOptions)
        self.menuY_Axis.setObjectName("menuY_Axis")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionQ = QtWidgets.QAction(MainWindow)
        self.actionQ.setCheckable(True)
        self.actionQ.setObjectName("actionQ")
        self.action2Theta = QtWidgets.QAction(MainWindow)
        self.action2Theta.setCheckable(True)
        self.action2Theta.setObjectName("action2Theta")
        self.actionLinear = QtWidgets.QAction(MainWindow)
        self.actionLinear.setObjectName("actionLinear")
        self.actionLog = QtWidgets.QAction(MainWindow)
        self.actionLog.setObjectName("actionLog")
        self.menuFile.addAction(self.actionExport)
        self.menuX_axis.addAction(self.actionQ)
        self.menuX_axis.addAction(self.action2Theta)
        self.menuY_Axis.addAction(self.actionLinear)
        self.menuY_Axis.addAction(self.actionLog)
        self.menuOptions.addAction(self.menuX_axis.menuAction())
        self.menuOptions.addAction(self.menuY_Axis.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Specular Scan"))
        self.loadSpecButton.setText(_translate("MainWindow", "Load Specular"))
        self.label_5.setText(_translate("MainWindow", "Background Scan"))
        self.loadBackButton.setText(_translate("MainWindow", "Load Background"))
        self.label_6.setText(_translate("MainWindow", "Slit Scan"))
        self.loadSlitButton.setText(_translate("MainWindow", "Load Slit"))
        self.label.setText(_translate("MainWindow", "Starting Q"))
        self.label_2.setText(_translate("MainWindow", "Ending Q"))
        self.label_8.setText(_translate("MainWindow", "Starting Q"))
        self.label_9.setText(_translate("MainWindow", "Starting Q"))
        self.footprintRangeFull.setText(_translate("MainWindow", "Full Range"))
        self.footprintRangeFromGraph.setText(_translate("MainWindow", "From Graph..."))
        self.footprintApply.setText(_translate("MainWindow", "Apply"))
        self.label_7.setText(_translate("MainWindow", "Correction Range"))
        self.footprintCalcGuess.setText(_translate("MainWindow", "Guess"))
        self.footprintCalcFromGraph.setText(_translate("MainWindow", "From Graph..."))
        self.label_3.setText(_translate("MainWindow", "Footprint Correction"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuX_axis.setTitle(_translate("MainWindow", "X-Axis"))
        self.menuY_Axis.setTitle(_translate("MainWindow", "Y-Axis"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionExport.setText(_translate("MainWindow", "Export..."))
        self.actionQ.setText(_translate("MainWindow", "Q"))
        self.action2Theta.setText(_translate("MainWindow", "2Θ"))
        self.actionLinear.setText(_translate("MainWindow", "Linear"))
        self.actionLog.setText(_translate("MainWindow", "Log"))

from pyqtgraph import PlotWidget
